services:
  pdq-frontend:
    container_name: pdq-frontend
    profiles: ['production']
    build:
      context: ./client/
      dockerfile: '.Dockerfile.${ENVIRONMENT}'
    volumes:
      - './client/:/app'
      - '/app/node_modules'
    ports:
      - 5100:5100
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ENVIRONMENT
      - API_URL
      - FRONTEND_URL
    depends_on:
      - pdq-api
    restart: unless-stopped
  pdq-api:
    container_name: pdq-api
    profiles: ['production', 'development']
    build:
      context: ./server/
      dockerfile: .Dockerfile
    depends_on:
      - postgres16
    environment:
      API_URL: '${API_URL}'
      FRONTEND_URL: '${FRONTEND_URL}'
      DATABASE_URL: postgres://postgres:newPassword@postgres:5432/pdq
      NODE_ENV: '${ENVIRONMENT}'
      AVATAR_PATH: '${AVATAR_PATH}'
      AVATAR_URL: '${AVATAR_URL}'
      TOKEN: '${TOKEN}'
      PORT: 5101
      WAIT_HOSTS: postgres16:5432
    ports:
      - '5101:5101'
    volumes:
      - ./static:/var/pdq/static
      - ./server/src:/usr/app/src
      - ./server/nodemon.json:/usr/app/nodemon.json
      - ~/.pdq/avatars:/var/pdq/avatars
    restart: unless-stopped
  postgres16:
    container_name: postgres16
    profiles: ['production', 'development']
    image: postgres:16-alpine
    ports:
      - target: 5432
        published: 5102
    volumes:
      - ~/.pdq/postgres16/:/var/lib/postgresql/data
      - ./server/src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newPassword
      POSTGRES_DB: pdq
  # Legacy postgres for migration purposes only
  postgres:
    container_name: postgres
    profiles: ['upgrade']
    image: postgres:14.2-alpine
    ports:
      - target: 5432
        published: 5102
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./server/src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    restart: never
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newPassword
      POSTGRES_DB: pdq
volumes:
  db-data:
  pgadmin-data:
